### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by RichardProsser** [stephenmcd/filebrowser-safe#96]
I have followed the instructions given at http://mezzanine.jupo.org/docs/overview.html#installation:

`
$ pip install mezzanine

$ mezzanine-project project_name

$ cd project_name

$ python manage.py createdb --noinput
`
which results in the above error:

`
C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mezzanine\utils\conf.py:61: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mezzanine\conf\models.py", line 7, in <module>
    from mezzanine.core.models import SiteRelated
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mezzanine\core\models.py", line 24, in <module>
    from mezzanine.core.fields import RichTextField, OrderField
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mezzanine\core\fields.py", line 103, in <module>
    settings.PACKAGE_NAME_FILEBROWSER)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mezzanine\utils\importing.py", line 23, in import_dotted_path
    module = import_module(module_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\filebrowser_safe\fields.py", line 17, in <module>
    from filebrowser_safe.settings import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\filebrowser_safe\settings.py", line 15, in <module>
    DEFAULT_PATH_TINYMCE = tinymce.settings.JS_ROOT + '/'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

`
pip freeze:
`
appdirs==1.4.3
asgi-redis==1.3.0
asgiref==1.1.1
attrs==16.3.0
autobahn==0.18.1
autoenv==1.0.0
Automat==0.5.0
beautifulsoup4==4.6.0
bleach==2.0.0
channels==1.1.3
chardet==3.0.3
click==6.7
colorama==0.3.7
constantly==15.1.0
coverage==4.3.4
daphne==1.2.0
decorator==4.0.11
dj-database-url==0.4.2
Django==1.10.7
django-contrib-comments==1.8.0
django-extensions==1.7.8
django-organizations==0.9.1
django-tinymce==2.6.0
filebrowser-safe==0.4.7
Flask==0.12.1
future==0.16.0
grappelli-safe==0.4.6
gunicorn==19.6.0
haikunator==2.1.0
html5lib==0.999999999
incremental==16.10.1
ipython==6.0.0
ipython-genutils==0.2.0
itsdangerous==0.24
jedi==0.10.2
Jinja2==2.9.6
MarkupSafe==1.0
Mezzanine==4.2.3
msgpack-python==0.4.8
oauthlib==2.0.2
olefile==0.44
packaging==16.8
pbr==3.0.0
pickleshare==0.7.4
Pillow==4.1.1
prompt-toolkit==1.0.14
psycopg2==2.7.1
py==1.4.33
Pygments==2.2.0
pyparsing==2.2.0
pypiwin32==220
pytest==3.0.7
pytest-cov==2.4.0
pytz==2017.2
redis==2.10.5
requests==2.9.1
requests-oauthlib==0.8.0
simplegeneric==0.8.1
six==1.10.0
stevedore==1.21.0
traitlets==4.3.2
Twisted==17.1.0
txaio==2.6.2
tzlocal==1.4
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.1
whitenoise==3.3.0
zope.interface==4.3.3
`
The directory/file structure does not look right to me (no templates etc.):
`
$ ll
total 44
drwxr-xr-x 1 User 197610     0 May 20 20:05 ../
-rw-r--r-- 1 User 197610    63 May 20 20:05 .gitignore
-rw-r--r-- 1 User 197610    93 May 20 20:05 .hgignore
-rw-r--r-- 1 User 197610 21955 May 20 20:05 fabfile.py
-rwxr-xr-x 1 User 197610   376 May 20 20:05 manage.py*
-rw-r--r-- 1 User 197610    17 May 20 20:05 requirements.txt
-rw-r--r-- 1 User 197610     0 May 20 20:05 __init__.py
drwxr-xr-x 1 User 197610     0 May 20 20:05 deploy/
drwxr-xr-x 1 User 197610     0 May 20 20:05 ./
drwxr-xr-x 1 User 197610     0 May 20 20:06 project_name/

`
`
$ ll project_name/
total 33
drwxr-xr-x 1 User 197610     0 May 20 20:05 ../
-rw-r--r-- 1 User 197610  1609 May 20 20:05 local_settings.py
-rw-r--r-- 1 User 197610 11641 May 20 20:05 settings.py
-rw-r--r-- 1 User 197610  4272 May 20 20:05 urls.py
-rw-r--r-- 1 User 197610   501 May 20 20:05 wsgi.py
-rw-r--r-- 1 User 197610     0 May 20 20:05 __init__.py
drwxr-xr-x 1 User 197610     0 May 20 20:06 ./
drwxr-xr-x 1 User 197610     0 May 20 20:06 __pycache__/

`
`
$ python -V
Python 3.6.1
`

- Previously I had used virtualenv but that was no better.
- I am using 'git bash' (MINGW64) on WIndows 10.
- I am new to Mezzanine, with a fair knowledge of DJango and good Python experience.

Have I missed something?

**Comment by RichardProsser** [comment]
I set `ALLOWED_HOSTS = ['localhost']` but got essentially the same result.

**Comment by ryneeverett** [comment]
I'm not sure why a `tinymce` module would be in your global namespace. Did you `pip install tinymce` by chance? I suspect that section of code is deprecated but not usually hit since the `import tinymce.settings` line raises an `ImportError` and skips to the next section.

**Comment by sanastasiou** [comment]
I just forked the mezzanine master and run setup.py to install it. Still getting this exact same error.
